---
- name: Filter Linux Users Playbook
  hosts: all
  become: yes
  tasks:
    - name: Filter users from /etc/passwd
      shell: "grep -E '^[^:]+:.*:[^:]*[KCI][^:]*:' /etc/passwd | grep -v -E '^(cp6ipat1|qualys|servicenow_sshuser|unxqscan_fmo|unxqscan|unixsa|nobody|systemd-coredump|clevis|idadmin|dnsmasq):'"
      register: filtered_users

    - name: Display filtered users
      debug:
        var: filtered_users.stdout_lines
    - name: Save filtered users to a file
      copy: 
        content: "{{ filtered_users.stdout }}"
        dest: /tmp/filtered_users.txt  
        mode: '0644'
    - name: Expire passwords for filtered users
      shell: "chage -d 0 {{ item.split(':')[0] }}"
      loop: "{{ filtered_users.stdout_lines }}"
      when: filtered_users.stdout_lines is defined and filtered_users.stdout_lines | length > 0
      ignore_errors: yes
    - name: Notify if no users found
      debug:
        msg: "No users found matching the criteria."
      when: filtered_users.stdout_lines is not defined or filtered_users.stdout_lines | length == 0
      ignore_errors: yes
          
