---
- name: Filter Linux Users Playbook
  hosts: all
  become: yes
  tasks:
    - name: Filter users from /etc/passwd
      shell: "grep -E '^[^:]+:.*:[^:]*[KCI][^:]*:' /etc/passwd | grep -v -E '^(cp6ipat1|qualys|unxqscan|unixsa|nobody|systemd-coredump|clevis|idadmin|dnsmasq):'"
      register: filtered_users

    - name: Display filtered users
      debug:
        var: filtered_users.stdout_lines
    - name: Expire passwords of filtered users
  shell: |
    chage -d 0 {{ item.split(':')[0] }}
  loop: "{{ filtered_users.stdout_lines }}"
  when: filtered_users.stdout_lines is defined and filtered_users.stdout_lines | length > 0
  register: chage_results
  ignore_errors: yes  # Ignore errors if any user command fails

- name: Display results of password expiry
  debug:
    msg: "{{ chage_results }}"
  when: chage_results is defined

          
