---
- name: Expire passwords for users based on specific conditions
  hosts: all
  become: yes  # Ensure to run with elevated privileges if necessary
  gather_facts: no  # Disable fact gathering
  tasks:
    - name: Get content of /etc/passwd
      command: cat /etc/passwd
      register: passwd_content
      changed_when: false  # Prevent Ansible from marking it as a change

    - name: Debugging: Show result of cat /etc/passwd
      debug:
        msg: "{{ passwd_content.stdout }}"
        
    - name: Extract users based on password status and exclusions
      set_fact:
        users_to_expire: >-
          {{
            passwd_content.stdout.split('\n') | 
            select('match', '^[^:]+:.*:[^:]*[KCI][^:]*:') | 
            select('match', '^((?!cp6ipat1|qualys|unxqscan|unixsa|nobody|systemd-coredump|clevis|idadmin|dnsmasq).)*$') | 
            map('regex_replace', '^(.*):.*$', '\\1') | 
            list
          }}

    - name: Display users to expire
      debug:
        msg: "{{ users_to_expire }}"
