---
- name: Filter Linux Users Playbook
  hosts: all
  become: yes
  tasks:
    - name: Filter users from /etc/passwd
      shell: "grep -E '^[^:]+:.*:[^:]*[KCI][^:]*:' /etc/passwd | grep -v -E '^(cp6ipat1|qualys|unxqscan|unixsa|nobody|systemd-coredump|clevis|idadmin|dnsmasq):'"
      register: filtered_users

    - name: Display filtered users
      debug:
        var: filtered_users.stdout_lines
