---
- name: Update PAM configuration for password policies and enforce root password policy
  hosts: all
  become: yes
  tasks:

    
    # Step 1: Ensure minlen, dcredit, ucredit, ocredit, lcredit, minclass are set in /etc/pam.d/system-auth
    - name: Ensure minlen, dcredit, ucredit, ocredit, lcredit, minclass are set in /etc/pam.d/system-auth
      lineinfile:
        path: /etc/pam.d/system-auth
        regexp: '^password\s+required\s+pam_pwquality.so'
        line: 'password    required                                pam_pwquality.so retry=3 minlen=15 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1 minclass=4 enforce_for_root'
        state: present
        backup: yes

    # Step 2: Ensure minlen, dcredit, ucredit, ocredit, lcredit, minclass are set in /etc/pam.d/password-auth
    - name: Ensure minlen, dcredit, ucredit, ocredit, lcredit, minclass are set in /etc/pam.d/password-auth
      lineinfile:
        path: /etc/pam.d/password-auth
        regexp: '^password\s+required\s+pam_pwquality.so'
        line: 'password    required                                pam_pwquality.so retry=3 minlen=15 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1 minclass=4 enforce_for_root'
        state: present
        backup: yes

    # Step 3: Remove pam_cracklib.so from /etc/pam.d/system-auth
    - name: Remove pam_cracklib.so from /etc/pam.d/system-auth
      lineinfile:
        path: /etc/pam.d/system-auth
        regexp: '^\s*password\s+required\s+pam_cracklib.so'
        state: absent
        

    # Step 4: Remove pam_cracklib.so from /etc/pam.d/password-auth
    - name: Remove pam_cracklib.so from /etc/pam.d/password-auth
      lineinfile:
        path: /etc/pam.d/password-auth
        regexp: '^\s*password\s+required\s+pam_cracklib.so'
        state: absent
  

    # Step 5: Ensure enforce_for_root is set in /etc/security/pwquality.conf
    - name: Ensure enforce_for_root is set in /etc/security/pwquality.conf
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^enforce_for_root'
        line: 'enforce_for_root'
        state: present
        backup: yes

    
